### ISSUE TITLE
Failed to save player data

### ISSUE THREAD

**Issue by matusevichy** [The-Fireplace-Minecraft-Mods/Grand-Economy#1]
after add to my server mods Clans and Grand Economy there was a problem with saving player data. in debug.log writes [Server thread/WARN] [net.minecraft.world.storage.SaveHandler]: Failed to save player data for matusevichy. after deleting these mods the problem has disappeared.
[debug-4.log.gz](https://github.com/The-Fireplace-Minecraft-Mods/Grand-Economy/files/2974030/debug-4.log.gz)
[2019-03-16-4.log.gz](https://github.com/The-Fireplace-Minecraft-Mods/Grand-Economy/files/2974031/2019-03-16-4.log.gz)

**Comment by The-Fireplace** [comment]
Next time, please follow the instructions. Providing version numbers and pasting logs aren't hard to do, and they make it far easier for me to fix the issue.
Forge 14.23.5.2768
Grand Economy 1.0.0
Clans 1.1.0
[latest.log](https://paste.ubuntu.com/p/CNpwDTwRVn/)
[debug.log](https://paste.ubuntu.com/p/n6H9NQDzjY/)

**Comment by The-Fireplace** [comment]
I just tested, and was unable to reproduce the issue. Please try again with Clans 1.1.5 and let me know if the issue persists.

**Comment by matusevichy** [comment]
Thanks. With clans 1.1.5 this problem disappeared.
