### ISSUE TITLE
Can't Load Mod in Server

### ISSUE THREAD

**Issue by PMeridian1** [The-Fireplace-Minecraft-Mods/Grand-Economy#10]
**Describe the bug**
Grand Economy isn't being loaded in the Minecraft server I'm building. It says it can't find the mods.toml file. The server still runs, just without the mod.

**To Reproduce**
1. Load mod.jar into mods folder
2. Start the server. The error is displayed as it tries to load the installed mods.

**Output from the server as it tries to load the mod**
[main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file Mod File: D:\Minecraft Forge Server\mods\GrandEconomy-1.15.2-1.5.3.jar is missing mods.toml file
[main/WARN] [ne.mi.fm.lo.mo.ModDiscoverer/SCAN]: File D:\Minecraft Forge Server\mods\GrandEconomy-1.15.2-1.5.3.jar has been ignored - it is invalid

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.15.2
 - Mod Version: 1.5.3
 - Forge: 31.1.0
 - Fabric Loader/Fabric API: Not using Fabric
 - java version 1.8.0_241 (not requested, but in case it matters)

What I find so strange about this is that I added some other random mods (mostly as a sanity check) and they all load fine. No "missing mods.toml" message with them at all. I went ahead and opened up the .jar of the other mods to compare files with Grand Economy, and they all have mods.toml files in the same place as Grand Economy. So I really don't see how Forge is missing it, but I am new to this.

Also, and maybe this is a big clue as to what's going on, here's another line from the server output:

[Server thread/WARN] [ne.mi.fm.se.ServerModLoader/LOADING]: Mods loaded with 1 warnings
[Server thread/WARN] [ne.mi.fm.se.ServerModLoader/LOADING]: File GrandEconomy-1.15.2-1.5.3.jar is a Fabric mod and cannot be loaded

If I put the Grand Economy .jar in my local Minecraft mods folder, I get the same message when I launch the game. It's like it thinks it's Fabric only and doesn't bother looking for the Forge files.

Sorry if this is just a config mistake I made and not an actual bug, I just didn't know what else to do. Google isn't getting me anywhere at this point.

**Comment by The-Fireplace** [comment]
Sorry about that, something went horribly wrong in my build script resulting in a very messed up file that I doubt would have worked on either loader. I've gotten around that issue now, and version 1.5.4 is on CurseForge with the fix.

**Comment by PMeridian1** [comment]
Awesome! It seems to be working just fine now.

Thank you so much!
