### ISSUE TITLE
Grand Economy commands unrecognized by server

### ISSUE THREAD

**Issue by PMeridian1** [The-Fireplace-Minecraft-Mods/Grand-Economy#11]
**Describe the bug**
Really sorry to open another ticket so soon. The "/wallet take" command isn't adjusting the target player's balance. "/wallet add" and "/wallet give" both work when typed in-game. However, if typed directly into the server console, _all_ GE commands are unrecognized except for "/gehelp."

**To Reproduce**
1. Start server
2. Start Minecraft
3. Login to server
4. Type in chat box "/wallet take [playername] <integer>"
5. It outputs a message that says the number was taken from the balance, but the "/balance" command shows no change. (see screenshot)

If the command is done by a command block, nothing happens at all.

**Logs/Screenshots/Videos**
From server console:
/wallet give PostMeridian 100
[Server thread/INFO] [minecraft/DedicatedServer]: Unknown command
[Server thread/INFO] [minecraft/DedicatedServer]: /wallet give PostMeridian 100<--[HERE]
/wallet add PostMeridian 100
[Server thread/INFO] [minecraft/DedicatedServer]: Unknown command
[Server thread/INFO] [minecraft/DedicatedServer]: /wallet add PostMeridian 100<--[HERE]
/wallet take PostMeridian 100
[Server thread/INFO] [minecraft/DedicatedServer]: Unknown command
[Server thread/INFO] [minecraft/DedicatedServer]: /wallet take PostMeridian 100<--[HERE]

Screenshot from within Minecraft:
![GE_Take](https://user-images.githubusercontent.com/62862579/78318730-23a0b680-752b-11ea-8101-9e174243abdb.png)

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.15.2
 - Mod Version: 1.5.4
 - Forge: 31.1.0
 - Fabric Loader/Fabric API: Not applicable

**Comment by The-Fireplace** [comment]
No need to apologize! Please, open as many tickets as you need, I'd much
rather know about issues so I can fix them.

**Comment by The-Fireplace** [comment]
Ok, so for server console, just so we're clear, did you type the commands without the slash?

**Comment by PMeridian1** [comment]
With our without the slash, the commands are unrecognized in the server console. gehelp is the only command the console recognizes.

In game, I believe all the commands work, except for /wallet take. It's been awhile since I tried them all.

**Comment by The-Fireplace** [comment]
Ok, thanks, just checking. I'll get it fixed soon.

**Comment by PMeridian1** [comment]
Awesome! Thank you so much

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod will only support Fabric going forward. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
