### ISSUE TITLE
 Request to operate the "Convert" command in command blocks

### ISSUE THREAD

**Issue by ghost** [The-Fireplace-Minecraft-Mods/Grand-Economy#14]
**Is your feature request related to a problem? Please describe.**
It is not possible to use the / convert command in a command block, because when you check the following syntax "convert @p" the console mentions "you don't have permission to use this command".
And if you use the syntax "/ execute @p ~ ~ ~ convert" the console mentions "Error to execute convert with @player"

**Describe the solution you'd like**
I would like to use the / convert command or find some way to use the / execute command to convert the item in hand to money for the selected enderpay or economy using a command block

**Describe alternatives you've considered**
Another alternative would be to find a way to execute the / convert command through an NPC of the customNPC´s mod.

**Comment by The-Fireplace** [comment]
I am no longer supporting the /convert command, and recommend switching to Grand Exchange for a more flexible way to do the same thing. It can't currently accept a player for its commands either, but I plan to make that possible there sometime soon.
