### ISSUE TITLE
Add a command to see the base price of an item

### ISSUE THREAD

**Issue by DarthJahus** [The-Fireplace-Minecraft-Mods/Grand-Economy#15]
I've created the issue [here](https://github.com/The-Fireplace-Minecraft-Mods/Grand-Exchange/issues/31) but it would - maybe - better go in Grand-Economy. Would probably be simpler to implement.

**Comment by The-Fireplace** [comment]
No, this definitely belongs on Grand Exchange, the convert command on Grand Economy will no longer be getting support since Grand Exchange has all the same functionality and more.
