### ISSUE TITLE
Just installed for 1.15.2 and cannot access a region stick. No sticks register for region. 

### ISSUE THREAD

**Issue by sarawhispers** [The-Fireplace-Minecraft-Mods/Grand-Economy#16]
**Describe the bug**

**To Reproduce**

**Logs/Screenshots/Videos**
Providing logs can be helpful in solving issues. If you crashed, you _must_ provide a crash report and/or a log file. Logs are usually named something like latest.log, debug.log, fml-client-latest.log, or fml-server-latest.log and can be found in the logs folder. If you have one of these, please paste it to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com/) and provide the link here. Do *not* attach the log file directly.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: [e.g. 1.15.2]
 - Mod Version: [e.g. 2.0.1]
 - Forge (If applicable) [e.g. Forge 28.1.116]
 - Fabric Loader (If applicable) [e.g. Fabric Loader 0.7.6+build.179]
 - Fabric API (If applicable) [e.g. Fabric API 0.4.29 build 290]

**Comment by The-Fireplace** [comment]
A region stick? What are you talking about? And please fill out the information requested in the template or I cannot help you.
