### ISSUE TITLE
Format currency value text with a thousands seperator

### ISSUE THREAD

**Issue by Tophattingson** [The-Fireplace-Minecraft-Mods/Grand-Economy#17]
**Is your feature request related to a problem? Please describe.**
It is difficult to quickly read currency values when they're longer than 6 digits.

**Describe the solution you'd like**
Format currency value text with commas as the thousands separator.

**Describe alternatives you've considered**
Some countries use a space or a full stop as the thousands separator instead of a comma.

**Comment by Tophattingson** [comment]
Minecraft localisation does not consider whether to use a comma or full stop as the thousands separator, most easily seen in the statistics screen. Seems to always use comma.

**Comment by The-Fireplace** [comment]
Done in the update I'm currently working on, Grand Economy 2.0.0.
