### ISSUE TITLE
Return of /convert command

### ISSUE THREAD

**Issue by Hydraheads** [The-Fireplace-Minecraft-Mods/Grand-Economy#21]
**Is your feature request related to a problem? Please describe.**
I understand that in the latest grand economy, the feature to use /convert was removed, and it is suggested to use grand exchange for that feature. However, I feel this is pretty convoluted, as the commands for players accepting an admin buy offer are way more confusing and involved.  

Players would have to memorize the offer ids now for each individual converted item.  Additionally, requiring the installation of grand exchange adds more weight to a server, especially if the server has no need for economy other than for land claims. Finally, /convert made integration of land claims possible on newly generated sp worlds without forcing players to op themselves and set up new shops. This new structure does not allow that.

**Describe the solution you'd like**
Finding a way to re-add /convert in GE 2.0.0

**Describe alternatives you've considered**
- allowing clans 2.0.0 to latch on to earlier versions of Grand Economy
- a way in Grand Exchange for users to sell a universalized item without id memorization, for potentially tons of items
- a way to register Grand Exchange admin sells in the config so they apply to every world

**Additional context**
N/A

**Comment by The-Fireplace** [comment]
Done in Grand Economy 2.1.0
