### ISSUE TITLE
[1.12.2] Config not working correctly

### ISSUE THREAD

**Issue by teagan75** [The-Fireplace-Minecraft-Mods/Grand-Economy#22]
**Describe the bug**
When I bridge your mod with EnderPay, and change the config to enforce non-negative accounts, it doesn't honor that.

**To Reproduce**
1. dl your mod and enderpay
2. change grand economy config to enforce non-negative accounts
3. Purchase an item that costs more than you have in your balance.
4. See a negative balance

**Logs/Screenshots/Videos**
I will try and get you a log

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: GrandEconomy-1.12.2-2.0.0
 - Forge:  14.23.5.2854

**Comment by The-Fireplace** [comment]
Will you make a paste of your config as well?

**Comment by teagan75** [comment]
For my logs, does it have to be when I am in the negative or go in the negative? I am currently not in the negative. Here is my config:

https://pastebin.com/AGWYC7J7

**Comment by teagan75** [comment]
To be more specific, when players use the banknotes from enderpay it doesn’t go in the negative. Only when using the /wallet give|take command

**Comment by Caltinor** [comment]
I think I found out why.  The `economyWrapper` does a check for the config value:
https://github.com/The-Fireplace-Minecraft-Mods/Grand-Economy/blob/93687402f39d7ccc20b32b7ed2caba225f5dab08/src/main/java/the_fireplace/grandeconomy/GrandEconomy.java#L65-L72

But when that method is invoked it still returns false if the balance outcome would be negative
https://github.com/The-Fireplace-Minecraft-Mods/Grand-Economy/blob/93687402f39d7ccc20b32b7ed2caba225f5dab08/src/main/java/the_fireplace/grandeconomy/econhandlers/ge/GrandEconomyEconHandler.java#L42-L43

**Comment by The-Fireplace** [comment]
This really isn't a major issue, wallet give and take are admin commands. Since this is EnderPay we're dealing with, I have to wonder whether it's EnderPay's or Grand Economy's wallet command that's getting run. In any event, Forge is no longer being supported, and the mod will only support Fabric going forward. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
