### ISSUE TITLE
[1.12.2] It's not giving me a folder for grandeconomy-extra

### ISSUE THREAD

**Issue by JadianRadiator** [The-Fireplace-Minecraft-Mods/Grand-Economy#24]
**Describe the bug**
1.12.2 Grand Economy isn't giving me a folder for grandeconomy-extra

**To Reproduce**
1. Download and run 1.12.2 Minecraft with the Grand Economy mod
2. Boot the instance
3. Once you reach Minecraft's main menu, shut down the game
4. Go to the config folder for the test instance
5. See the distinct lack of a config/grandeconomy-extra folder

**Logs/Screenshots/Videos**
Providing logs can be helpful in solving issues. If you crashed, you _must_ provide a crash report and/or a log file. Logs are usually named something like latest.log, debug.log, fml-client-latest.log, or fml-server-latest.log and can be found in the logs folder. If you have one of these, please paste it to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com/) and provide the link here. Do *not* attach the log file directly.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: [e.g. 1.15.2]
1.12.2
 - Mod Version: [e.g. 2.0.1]
2.0.0
 - Forge (If applicable) [e.g. Forge 28.1.116]
14.23.5.2854
 - Fabric Loader (If applicable) [e.g. Fabric Loader 0.7.6+build.179]
 - Fabric API (If applicable) [e.g. Fabric API 0.4.29 build 290]

**Comment by The-Fireplace** [comment]
The /convert command was removed in Grand Economy 2.0.0, in favor of using Grand Exchange for similar functionality. As such, the grandeconomy-extra folder is no longer needed.
