### ISSUE TITLE
Balance NaN

### ISSUE THREAD

**Issue by TrevorBagels** [The-Fireplace-Minecraft-Mods/Grand-Economy#27]
There aren't any errors or anything, and I have no idea what caused this issue, but my balance is NaN for some reason, which also gives me infinite money. A simple check to see if someone's balance is NaN would probably fix the issue, and maybe storing a value for each players last known balance would make it easy to restore their previous balance if it goes NaN.

**Comment by The-Fireplace** [comment]
What mod version? And what is the economy bridge setting set to?

**Comment by TrevorBagels** [comment]
Using GrandEconomy-1.12.2-2.0.0 and GrandExchange-1.12.2-1.5.0
economy bridge = none

**Comment by The-Fireplace** [comment]
Does this happen again after you set the balance or was this just a one time thing? Also, updates are available for both mods.

**Comment by TrevorBagels** [comment]
It happens even after I set the balance, but I'm not sure as to what caused it to happen. I wiped the server about a day ago, and now I'm using Grand Economy (the latest version) with Oxygen, and so far I haven't noticed any issues. I'll be sure to post here if I notice anything related to the NaN balance.

**Comment by The-Fireplace** [comment]
Grand Economy 2.1.2 should prevent this from causing problems. Still need to find where NaN was coming from but it won't be allowed to hit the account now.

**Comment by TrevorBagels** [comment]
Does it just set the balance back to zero? Or does it keep track of the player's last balance? One of my players is experiencing their balance dropping to zero for some reason, although it could be related to the oxygen mod.

**Comment by The-Fireplace** [comment]
If something tries to change it to NaN Grand Economy prevents it, so it will just keep the previous balance.
