### ISSUE TITLE
pixelmon-vault

### ISSUE THREAD

**Issue by erposse90** [The-Fireplace-Minecraft-Mods/Grand-Economy#28]
hi can i use this mod to link pixelmon economy to vault? if so, how?

**Comment by The-Fireplace** [comment]
You can make plugins that use Vault use Pixelmon currency, but you can't make Pixelmon use Vault-based currency.
To make Vault plugins use Pixelmon currency, set Grand Economy's economy bridge option to pixelmon and install the [Grand Economy Vault Compat](https://www.curseforge.com/minecraft/bukkit-plugins/grand-economy-vault-compat) plugin.
