### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by erposse90** [The-Fireplace-Minecraft-Mods/Grand-Economy#29]
the list of permissions is missing .. when i use geconomy as op i have all the commands, but my players don't

**Comment by erposse90** [comment]
I found the permissions thanks to luckperms, they are:
-commandpay.pay
-commandbalance.balance
-commandwallet.wallet

**Comment by The-Fireplace** [comment]
Those are not permissions I added, they are probably generic permissions created by another mod or plugin for every command.
