### ISSUE TITLE
Pay offline players

### ISSUE THREAD

**Issue by OS-Void** [The-Fireplace-Minecraft-Mods/Grand-Economy#32]
**Is your feature request related to a problem? Please describe.**
1.17 has been slacking economy mods, and gunpowder is too intrusive/not stable to be used, but one thing I liked from gunpowder's currency was the ability to pay offline players.

Which helps small servers that are based in trust (community/friends servers) not having Signshop shops, so we can pay offline players and take items.

This feature shouldn't be that hard to implement as it already saves balances with UUIDs which is all it needs to transfer funds.

**Comment by The-Fireplace** [comment]
Forgot to close the issue when it happened, but it's done
