### ISSUE TITLE
[Feature] Supprt Krist Pay

### ISSUE THREAD

**Issue by Merith-TK** [The-Fireplace-Minecraft-Mods/Grand-Economy#36]
https://github.com/tmpim/KristPay < plugin for 1.12

Just simply would like players to beable to use krist as currency on servers, much like how the switchcraft handles payment

**Comment by The-Fireplace** [comment]
This appears to be a Sponge plugin. 1.12.2 should have support for Sponge-based economies already, just set the economy bridge to "sponge"

**Comment by Merith-TK** [comment]
it doenst work quite like that

Krist is a Minecraft Specific Crypto Currency, meaning it connects to a blockchain,
all the plugin does is facilitate transfering krist funds

**Comment by The-Fireplace** [comment]
Adding support for directly using cryptocurrency is outside the scope of this mod. If the adapter works with Sponge's economy API, then they should work fine together. If not, then it's likely something that won't integrate well with Grand Economy either.
