### ISSUE TITLE
economyBridge Compatibility Request - Diamond Economy

### ISSUE THREAD

**Issue by ProfDarkside** [The-Fireplace-Minecraft-Mods/Grand-Economy#38]
Per your suggestion in the comments, I'd like to request **Diamond Economy** be made compatible for the economyBridge option. With Grand Economy, Sewing Machine Utilities (Requested by another user already), and Diamond Economy being just about the only server-sided economy mods available to Fabric, I'd love to be able to use them all together
Thank You!

**Comment by The-Fireplace** [comment]
Done in Grand Economy 6.0.0. Give it a try and let me know if you have issues.
