### ISSUE TITLE
internal exception error in 1.19 server with Grandeconomy mod

### ISSUE THREAD

**Issue by duynh03** [The-Fireplace-Minecraft-Mods/Grand-Economy#41]
### Mod Version

6.0.0

### What mod loader(s) are you seeing the problem on?

Fabric

### Mod Loader Version

1.19

### Problem Description

After updating my server to 1.19 and installing the 1.19 version of grandeconomy, all my server members and I cannot join the server and are provided with an internal exception error message. Here is some screenshots:
![image](https://user-images.githubusercontent.com/110436568/182272872-77aff391-2b1f-4d2c-a5ea-58fe5dfd3783.png)
![image](https://user-images.githubusercontent.com/110436568/182272882-55a2bcd5-e0d0-427a-afcb-75cc41d79709.png)
There are no error message in the server log either.

**Comment by The-Fireplace** [comment]
This is a known bug with Fireplace Lib, it doesn't work as server-side-only on 1.19 quite yet.

**Comment by The-Fireplace** [comment]
https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/issues/51

**Comment by The-Fireplace** [comment]
Should be fixed with Fireplace Lib 7.0.3
