### ISSUE TITLE
An event to track balance changes

### ISSUE THREAD

**Issue by AustereTony-MCMods** [The-Fireplace-Minecraft-Mods/Grand-Economy#7]
_MC version: 1.12.2_

Hello.

Grand Economy is a great option for implementing an economy for the server, and support for third-party platforms (like Sponge) is a great bonus.

I use Grand Economy to integrate third-party economies into my project (Oxygen). In my opinion, there is not enough opportunity to track a change in a player’s balance when this change occurs through Grand Economy (eg. chat commands). Could you add an event to track the player’s balance update and fire it when the balance changes inside the Grand Economy?

I need this to be able to synchronize the player’s balance with the client, if it was changed using the Grand Economy commands. At the moment, I have to use ASM transformers to implement hooks in your methods in order to track changes, which is not very convenient and not safe in case of Grand Economy update. Hooks with position: https://github.com/AustereTony-MCMods/Oxygen-Currency-Providers/blob/grand-economy/src/main/java/austeretony/oxygen_cp_ge/common/core/CurrencyProviderHooks.java

If you can add an event and provide the player's UUID, the old and new balance, it would be great.

Thank you.

**Comment by The-Fireplace** [comment]
I'm migrating the repo, I'll copy the issue over and tag you.
