### ISSUE TITLE
How can i change the /balance command to a custom command?

### ISSUE THREAD

**Issue by davizon200** [The-Fireplace-Minecraft-Mods/Grand-Economy#8]
I am using this mod and enderpay to haver 2 currencies in my server, and both mods use /balance as the command to check the current balance, how can i edit the current commands?
Enderpay is dead and inactive, thats why i posted my issue here!
Just changing it to /balance2 would fix my issue.

Sincerely,
Davizon200 / Alfkors.

**Comment by The-Fireplace** [comment]
Currently, you can't. Typically I'd expect that if you're using EnderPay with Grand Economy, you are making Grand Economy point to that currency, which would avoid the problem you're having.
