### ISSUE TITLE
Money conversion visual bug

### ISSUE THREAD

**Issue by MoHyB123** [The-Fireplace-Minecraft-Mods/Grand-Economy#9]
**Describe the bug**
It adds 32 credits when you add money to the clans balance. F.e. adding 100 credits will add 132 credits to the clans balance. Setting chunk claiming to cost money will also add the 32, f.e. setting it to cost 1000 to claim chunk it will cost 1032. Getting it back to your private balance it takes the 32 away again. 

**To Reproduce**
1. Install GE, Clans & Ender Pay
2. Set GE config to use Ender Pay
3. Create a clan
4. Use the command "addfunds" to add to the clans balance

**Versions:**
 - Minecraft: 1.12.2
 - Mod Version: 1.5.10
 - Forge: 14.23.5.2847

**Comment by The-Fireplace** [comment]
Update: Grand Economy 1.3.8
